/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.joker1007.kafka.streams.state;

public class Library {
  public boolean someLibraryMethod() {
    return true;
  }
}
